#!/bin/bash

./configure \
--with-features=huge \
--enable-largefile=yes \
--enable-cscope=yes \
--enable-multibyte \
--with-x=yes \
--enable-python3interp \
--enable-pythoninterp \
--enable-terminal \
--enable-gtk3-check \
--enable-gui=gnome3 \
--enable-luainterp \
--enable-fail-if-missing \
--prefix=/mnt/projetos/shareapps/vim \
--exec-prefix=/mnt/projetos/shareapps/vim

make VIMRUNTIMEDIR=/mnt/projetos/shareapps/vim/share/vim/vim81
make install

